version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-legacy-polyfills
    versions:
    - 0.7.0
    - 1.0.0
    - 1.1.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
  - dependency-name: gatsby-source-wordpress
    versions:
    - 3.11.0
    - 4.0.0
    - 4.0.1
    - 4.0.3
    - 4.0.4
    - 4.0.5
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.12.0
    - 2.12.1
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.14.0
    - 2.14.1
    - 2.14.2
    - 2.14.3
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.12.0
    - 2.12.1
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.11.0
    - 2.11.1
  - dependency-name: gatsby-plugin-canonical-urls
    versions:
    - 2.10.0
  - dependency-name: gatsby-transformer-json
    versions:
    - 2.11.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.12.0
  - dependency-name: cypress
    versions:
    - 6.3.0
  - dependency-name: gatsby-source-wordpress-experimental
    versions:
    - 7.0.3
